name: Go CI

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yml"

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/a-h/templ/cmd/templ@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just@1.40.0

      - name: Generate templ files
        run: templ generate

      - name: Lint (format, vet, lint)
        run: |
          just lint
          if [ $(git status --porcelain | wc -l) -gt 0 ]; then
            echo "Go files are not properly formatted. Please run 'just lint' and commit the changes."
            git status --porcelain
            exit 1
          fi

      - name: Run tests with coverage
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          # Equivalent to "just test-race" but with specific coverage output format for CI

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate templ files
        run: templ generate

      - name: Build
        run: just build
